DROP TABLE FIND;

CREATE TABLE FIND_BOARD(
    WRITE_NO NUMBER(10) PRIMARY KEY,
    NICKNAME VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    VIEWS NUMBER(10) DEFAULT 0,
    WRITE_DATE DATE DEFAULT SYSDATE,
    AGE NUMBER NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    GENDER VARCHAR2(100) NOT NULL,
    ID VARCHAR(100) NOT NULL
);


CREATE SEQUENCE FIND_BOARD_SEQ INCREMENT BY 1 MAXVALUE 1000;

CREATE TABLE FIND_RE(
RE_ID VARCHAR2(100) NOT NULL,
RE_COMENT VARCHAR2(300) NOT NULL,
WRITE_GROUP NUMBER,
RE_DATE DATE DEFAULT SYSDATE,
RE_NICK VARCHAR2(100) NOT NULL,
CONSTRAINT FK_FIND_RE_BOARD FOREIGN KEY(WRITE_GROUP) REFERENCES FIND_BOARD(WRITE_NO) ON DELETE CASCADE
);