 CREATE TABLE PROMO(
    SEQ NUMBER,
    SUBJECT VARCHAR2(200),
    CONTENT VARCHAR2(1000),
    NAME VARCHAR2(20),
    REG_DATE VARCHAR2(100),
    HIT NUMBER
    );

DESC PROMO;    
    
    
INSERT INTO PROMO (SEQ, SUBJECT, CONTENT, NAME, HIT) VALUES ('1', 'TEST_SUBJECT1', 'TEST', 'k', '0');

SELECT * FROM PROMO;

COMMIT;


CREATE TABLE PROMO_BOARD(
WRITE_NO NUMBER(10) PRIMARY KEY,
TITLE VARCHAR2(100),
CONTENT VARCHAR2(300),
SAVEDATE DATE DEFAULT SYSDATE,
HIT NUMBER(10) default 0,
IMAGE_FILE_NAME VARCHAR2(100),
ID VARCHAR2(20) NOT NULL
--CONSTRAINT FK_TEST FOREIGN key(id) REFERENCES membership(id) on delete cascade
);

CREATE SEQUENCE PROMO_BOARD_SEQ NOCACHE NOCYCLE;

DESC PROMO_BOARD;

COMMIT;

CREATE TABLE PROMO_REPLY(
ID VARCHAR2(100),
TITLE VARCHAR(100),
CONTENT VARCHAR2(300),
WRITE_GROUP NUMBER(10),
WRITE_DATE DATE DEFAULT SYSDATE
);

DESC PROMO_REPLY;

COMMIT;







